In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
print(pd.__version__)
print(np.__version__)

2.3.3
2.0.2

In [3]:
import os
print(os.listdir("/kaggle/input/datasets/shuofxz/titanic-machine-learning-from-disaster"))

['train.csv', 'test.csv']

In [4]:
df = pd.read_csv("/kaggle/input/datasets/shuofxz/titanic-machine-learning-from-disaster/train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# **Data Dictionary:****
# **Variable	   Definition	                      Key****
  survival	       Survival	                     0 = No, 1 = Yes
  pclass	       Ticket class	                 1 = 1st, 2 = 2nd, 3 = 3rd
   sex	             Sex	
   Age	           Age in years	
  sibsp	           # of siblings / spouses aboard the Titanic	
  parch	           # of parents / children aboard the Titanic	
  ticket	       Ticket number	
  fare	           Passenger fare	
  cabin	           Cabin number	
  embarked	      Port of Embarkation	         C = Cherbourg, Q = Queenstown, S = Southampton


# Data Dictionary

* pclass: A proxy for socio-economic status (SES)

1st = Upper
2nd = Middle
3rd = Lower
* age: Age is fractional if less than 1. If the age is estimated, is it in the form of xx.5

* sibsp: The dataset defines family relations in this way...

Sibling = brother, sister, stepbrother, stepsister
Spouse = husband, wife (mistresses and fiancés were ignored)
parch: The dataset defines family relations in this way...

* Parent = mother, father
 Child = daughter, son, stepdaughter, stepson
 Some children travelled only with a nanny, therefore parch=0 for them.

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
df.shape

(891, 12)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [12]:
df["Cabin"].value_counts().sum()

np.int64(204)

In [13]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [14]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [15]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [16]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [17]:
df["SibSp"].value_counts()

SibSp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

In [18]:
df.groupby("Pclass")["Survived"].sum()

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [19]:
df.groupby("Pclass")["Survived"].value_counts()

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

In [20]:
df.groupby("Sex")["Survived"].value_counts()

Sex     Survived
female  1           233
        0            81
male    0           468
        1           109
Name: count, dtype: int64

In [21]:
df.groupby("SibSp")["Survived"].value_counts()

SibSp  Survived
0      0           398
       1           210
1      1           112
       0            97
2      0            15
       1            13
3      0            12
       1             4
4      0            15
       1             3
5      0             5
8      0             7
Name: count, dtype: int64

In [22]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [23]:
df.describe(include='object')

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

# Notes:

PassengerId is useless, we will drop it
Pclass : we can consider it categorical by native ( We may change its dtype)
Sex: Males Count is bigger than Females Count
Embarked: 'S' City is the most frequent value

In [24]:
df.drop(["PassengerId", "Ticket", "Cabin"], axis=1, inplace=True)

In [25]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S

In [26]:
df = df[['Name', 'Sex',	'Age', 'SibSp',	'Parch', 'Fare', 'Embarked', 'Pclass', 'Survived']]
df.head()

,Name,Sex,Age,SibSp,Parch,Fare,Embarked,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,1,1
2,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S,1,1
4,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S,3,0

In [27]:
df.isna().sum()

Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
Pclass        0
Survived      0
dtype: int64

In [28]:
df.shape

(891, 9)

In [29]:
df1=df.copy()
df1

,Name,Sex,Age,SibSp,Parch,Fare,Embarked,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,1,1
2,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S,1,1
4,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S,3,0
...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,0,0,13.0000,S,2,0
887,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,S,1,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500,S,3,0
889,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000,C,1,1
890,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500,Q,3,0

In [30]:
df1["Age"]=df1["Age"].fillna(df1["Age"].mean())
df1

,Name,Sex,Age,SibSp,Parch,Fare,Embarked,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.000000,1,0,7.2500,S,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,71.2833,C,1,1
2,"Heikkinen, Miss. Laina",female,26.000000,0,0,7.9250,S,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,53.1000,S,1,1
4,"Allen, Mr. William Henry",male,35.000000,0,0,8.0500,S,3,0
...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.000000,0,0,13.0000,S,2,0
887,"Graham, Miss. Margaret Edith",female,19.000000,0,0,30.0000,S,1,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,23.4500,S,3,0
889,"Behr, Mr. Karl Howell",male,26.000000,0,0,30.0000,C,1,1
890,"Dooley, Mr. Patrick",male,32.000000,0,0,7.7500,Q,3,0

In [31]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      891 non-null    object
 1   Sex       891 non-null    object
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64
 4   Parch     891 non-null    int64
 5   Fare      891 non-null    float64
 6   Embarked  889 non-null    object
 7   Pclass    891 non-null    int64
 8   Survived  891 non-null    int64
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [32]:
df1.shape

(891, 9)

In [33]:
df1["Embarked"]=df1["Embarked"].fillna(df1["Embarked"].mode()[0])
df1

,Name,Sex,Age,SibSp,Parch,Fare,Embarked,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.000000,1,0,7.2500,S,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,71.2833,C,1,1
2,"Heikkinen, Miss. Laina",female,26.000000,0,0,7.9250,S,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,53.1000,S,1,1
4,"Allen, Mr. William Henry",male,35.000000,0,0,8.0500,S,3,0
...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.000000,0,0,13.0000,S,2,0
887,"Graham, Miss. Margaret Edith",female,19.000000,0,0,30.0000,S,1,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,23.4500,S,3,0
889,"Behr, Mr. Karl Howell",male,26.000000,0,0,30.0000,C,1,1
890,"Dooley, Mr. Patrick",male,32.000000,0,0,7.7500,Q,3,0

In [34]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      891 non-null    object
 1   Sex       891 non-null    object
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64
 4   Parch     891 non-null    int64
 5   Fare      891 non-null    float64
 6   Embarked  891 non-null    object
 7   Pclass    891 non-null    int64
 8   Survived  891 non-null    int64
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [35]:
df1.shape

(891, 9)